# Array of registry key paths

function Get-RegistryPaths {
    return @(
        "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment",
        "HKCU:\SYSTEM\CurrentControlSet\Policies\EarlyLaunch",
        "HKCU:\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter",
        "HKCU:\Software\Microsoft\Office\14.0\Word\Options",
        "HKCU:\Software\Microsoft\Office\14.0\Word\Options\WordMail",
        "HKCU:\Software\Microsoft\Office\15.0\Word\Options",
        "HKCU:\Software\Microsoft\Office\15.0\Word\Options\WordMail",
        "HKCU:\Software\Microsoft\Office\16.0\Word\Options",
        "HKCU:\Software\Microsoft\Office\16.0\Word\Options\WordMail",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient",
        "HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters",
        "HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters",
        "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters",
        "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters",
        "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
        "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager",
        "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Attachments",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Explorer",
        "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer",
        "HKLM:\SYSTEM\CurrentControlSet\Services\mrxsmb10",
        "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\LSASS.exe",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\CredentialsDelegation",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Rpc",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client",
        "HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Schedule",
        "HKLM:\SYSTEM\CurrentControlSet\Control",
        "HKLM:\SOFTWARE\Policies\Microsoft\Biometrics\FacialFeatures",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection",
        "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Diagnostics\DiagTrack",
        "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore",
        "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\GameDVR",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications",
        "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit",
        "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell",
        "HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile\Services\FileAndPrint",
        "HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\StandardProfile\Services\FileAndPrint",
        "HKLM:\SOFTWARE\Microsoft\Windows Defender\Real-Time Protection",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Network Connections",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Group Policy",
        "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon",
        "HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard",
        "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Printers",
		"HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\NoExiste"
    )
}
